### ISSUE TITLE
cluster support

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/grpc_mock#1]
*Problem*
* There are duplicate entries if we load the module multiple times
* In a distributed env, the `genserver` should be able to share state with other nodes
* The loaded compiled module code should be available on all the other nods

#### Tasks
- [x] remove duplication of modules
- [ ] make state shareable across load
- [x] share compiled module binary with all the nodes
- [ ] allow choosing cluster strategy through env variable (kubernetes, local, docker etc.)

**Comment by HandOfGod94** [comment]
The cluster support is way more complicated, esp. with kubernetes than what I initially anticipated. Better alternative is to create a single node app which is flexible enough to be configurable via UI as well as config files, and later on create a kube-operator for it.

**Comment by HandOfGod94** [comment]
Going ahead with kube-operator approach
