### ISSUE TITLE
support config based launching

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/grpc_mock#7]
- mock server should launch based dynamic grpc server based on yaml file

This will in future allow users to create kube-operator based on config files.

#### Tasks
- [x] add a new launch mode (non-interactive)
- [x] retrieve config file/configs from yaml
- [ ] disable proto upload route when config file is provided
